### ISSUE TITLE
ValueError when run

### ISSUE THREAD

**Issue by quiple** [dse/bitmapfont2ttf#2]
```cmd
Traceback (most recent call last):
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin\bitmapfont2ttf", line 45, in <module>
    bf2ttf.bitmapfont2ttf()
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bitmapfont2ttf.py", line 343, in bitmapfont2ttf
    self.loadBDF()
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bitmapfont2ttf.py", line 156, in loadBDF
    self.bdf = MyBDF(self.filename)
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bdf.py", line 60, in __init__
    self.read(filename)
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bdf.py", line 68, in read
    self.readFp(fp)
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bdf.py", line 77, in readFp
    self.readCharsFp(fp)
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bdf.py", line 158, in readCharsFp
    char = self.readCharFp(fp, args[0])
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bdf.py", line 185, in readCharFp
    char.bitmapData = self.readBitmapDataFp(fp)
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bdf.py", line 173, in readBitmapDataFp
    numBits = max(len(s) * 4 for s in bitmapData)
ValueError: max() arg is an empty sequence
```

It works normally when I try with GNU Unifont, but I get this error when I try with my BDF file.

What causes can expect?

And [here](https://github.com/quiple/galmuri/blob/main/dist/Galmuri11.bdf)'s my BDF file.

**Comment by quiple** [comment]
```bdf
BITMAP
ENDCHAR
```

```bdf
BITMAP
00
ENDCHAR
```

When I changed the above in my BDF file as below, the error was solved.

However, another error occurred this time.

```cmd
.\g11.bdf: milliem ascent = 875; descent = 125; self.font.em = 1000
StyleMap: is regular
StyleMap: 64
MacStyle: 0
Save Failed
Traceback (most recent call last):
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin\bitmapfont2ttf", line 45, in <module>
    bf2ttf.bitmapfont2ttf()
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bitmapfont2ttf.py", line 363, in bitmapfont2ttf
    self.save()
  File "C:\Users\user\Desktop\bdf2ttf\bitmapfont2ttf-master\bin/../lib\bitmapfont2ttf.py", line 183, in save
    self.font.generate(dest)
OSError: Font generation failed
```

**Comment by quiple** [comment]
I solved the error. The outline font generated normaly, but It looks doesn't work with `--no-trace` option. The generated TrueType font does not appear to contain any bitmap strike data.

I want to generate bitmap strike only.
